# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-stig-rhel-V-230284
  namespace: default
spec:
  tags: ["STIG","RHEL","V-230284",".shosts files"]
  message: "Alert! Access denied for .shosts files"
  selector:
    matchLabels:
       app: redhat
  file:
    severity: 5
    matchPatterns:
    - pattern: /**/.shosts
    action: Block
